[project]
name = "pdf-outline-extractor"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=6.29.5",
    "pymupdf>=1.26.3",
    "psutil>=6.1.0",
]
